### ISSUE TITLE
[Bug]: Suggestion Cards inside Fixed positioned elements

### ISSUE THREAD

**Issue by Sebah** [grammarly/grammarly-for-developers#588] opened 2023-04-10 06:52 UTC
### What package(s) are you seeing the problem in?

@grammarly/editor-sdk

### SDK version

v2.3.15 to v2.2.0

### Browser(s)

Firefox, Chrome, Safari, Microsoft Edge

### Operating system(s)

macOS

### Steps to reproduce

Inside any fixed element that has a limited viewport (height 598px in my scenario) via CSS.
The editor here is QuillJS.
(This bug is reproducible also on Windows, not only macOS) 

https://user-images.githubusercontent.com/202015/230843437-29c189bc-e6a5-41ce-9385-8bb5f899dd53.mp4

### What happened?

Inside a fixed position element which has its viewport cutoff by a fixed height and scrolling is enabled using overflow-y hidden, in certain scenarios the Suggestion Cards are not showing up and the said element start scrolling (see attached video).

I think, and this is a guess, the SDK can't read the actual height of the document as it only sees the first load as the targeted height. 

Reverting back to 2.1.0 doesn't cause the scroll anymore, but in the scenarios where the scrolling happened the Suggestion Cards are not visible.

### What did you expect to happen?

No scrolling and visible Suggestion Cards.

**Comment by cwatkins** [comment] 2023-04-10 17:13
Hi @Sebah,

Welcome to the community!

Thank you for reporting this issue. To better assist you, please share a minimal example reproducing the issue. You can [use this Quill-based Codesanbox.io example as a starting point](https://codesandbox.io/s/github/grammarly/grammarly-for-developers/tree/main/examples/editor-sdk-quill-imperative?file=/public/index.html). 

As an aside, I noticed that the Grammarly button is inside the text editor. You can [customize the position of the Grammarly button](https://developer.grammarly.com/docs/customization#custom-position) using the `<grammarly-button>` element.

**Comment by cwatkins** [comment] 2023-04-17 17:41
Hi @Sebah, 

I'm checking in to see if you've been able to reproduce your issue. If not, I recommend updating your CSS positioning rules to ensure that they exist on a parent element to both the Grammarly Text Editor Plugin and the editor of your text editor framework.

**Comment by cwatkins** [comment] 2023-04-26 21:29
Hi @Sebah, 

I'm closing this issue for now. It's known that [the position of the suggestion box can be covered if your CSS positioning rules aren't on a parent element](https://developer.grammarly.com/docs/diagnosing-issues#suggestion-cards-are-covered-or-positioned-wrong) of the Grammarly Text Editor plugin and the editor.  That behavior can include scrolling based on the size of the viewport. Our docs suggest that you put your positioning rules on a parent element because of that. If you find updating your CSS doesn't resolve the issue, please feel free to re-open this issue.

**Closed by cwatkins** 2023-04-26 21:29 UTC
Labels: bug
