### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by killian-dunne** [grammarly/grammarly-for-developers#302] opened 2022-11-16 10:03 UTC
### What package(s) are you seeing the problem in?

@grammarly/editor-sdk-react

### SDK version

2.0.2

### Browser(s)

Chrome

### Operating system(s)

macOS

### Steps to reproduce

Hi there, 

Using material UI and grammarly seems to cause an alignment issue. 

To reproduce: open the text box with a default value. ie: props.body must have a starting value before typing

```
import { TextField } from "@mui/material";
import { GrammarlyEditorPlugin } from "@grammarly/editor-sdk-react";

      <GrammarlyEditorPlugin clientId={process.env.REACT_APP_GRAMMARLY_ID}>
        <TextField
          label="Body"
          value={props.body}
          name="body"
          onChange={(e) => props.setBody(e.target.value)}
          multiline
          rows={expandedBox ? 12 : 3}
          variant="filled"
          placeholder="Compose email..."
          color="email"
          sx={{
            width: "100%",
            fontSize: "12px",
          }}
        />
      </GrammarlyEditorPlugin>
```

### What happened?

<img width="756" alt="image" src="https://user-images.githubusercontent.com/33072612/202150338-44cf29c1-2d7c-43cf-ac3d-0a96bf8b4b1f.png">

### What did you expect to happen?

<img width="756" alt="image" src="https://user-images.githubusercontent.com/33072612/202150671-55a396b5-cf96-4edb-a9cd-01631038195b.png">

**Comment by bgschiller** [comment] 2022-11-16 17:21
Hi @killian-dunne, thanks for the report. I do not see the same thing you are; the underlines appear in the right spot for me. Can you show me what I'm doing wrong? Here's the repo I put together to try to reproduce the bug: https://github.com/bgschiller/material-grammarly-bug/blob/main/src/App.tsx

**Comment by killian-dunne** [comment] 2022-11-16 18:21
Ahh thank you for your help! It turns out there was also a css item added as below. Probably not ideal behavior but at least I know how to resolve this. Cheers again! 
```
grammarly-editor-plugin {
  --grammarly-default-border-radius: 4px;
}
```

**Comment by AndrewDiMola** [comment] 2022-11-16 19:04
Hey @killian-dunne - I'm going to close this issue because it stemmed from a CSS property. Thanks so much for reporting and thanks @bgschiller for recreating the issue!

**Closed by AndrewDiMola** 2022-11-16 19:04 UTC
Labels: bug
