### ISSUE TITLE
[Bug]: introText not showing

### ISSUE THREAD

**Issue by karaburmication** [grammarly/grammarly-for-developers#453] opened 2023-01-25 15:30 UTC
### What package(s) are you seeing the problem in?

@grammarly/editor-sdk

### Browser(s)

Chrome

### Operating system(s)

None

### Steps to reproduce

```
<grammarly-editor-plugin config.introText="Some text here">
.....
</grammarly-editor-plugin>
```

For some reason, I still see Grammarly default intro text instead of my custom message from above

### What happened?

I see this message instead:

> Grammarly helps you write clearly and mistake-free. [Learn more](https://www.grammarly.com/)

### What did you expect to happen?

My custom message should appear

**Comment by AndrewDiMola** [comment] 2023-01-25 16:10
Hey @karaburmication - this configuration looks correct to me. Have you seen [this example](https://codesandbox.io/s/github/grammarly/grammarly-for-developers/tree/main/examples/editor-sdk-intro-text)? 

In the example, we include a reset button that calls these methods (to show intro text again):
* `localStorage.clear()`
* `sessionStorage.clear()`
* `window.location.reload()`

Can you share an example of the first suggestion card you see when you're looking for the introduction text? If you're able to do so in CodeSandbox, that would be a great help. My initial guess is that our "Connect your account" prompt is taking precedence, as it displays for certain types of writing suggestions.

**Comment by AndrewDiMola** [comment] 2023-01-27 21:17
@karaburmication - Let us know if you can provide more context!

Would love to help you figure out where the introduction text is displaying as intended.

**Comment by AndrewDiMola** [comment] 2023-02-03 16:44
Hey @karaburmication, I'm closing this issue because it's been a week since we've heard back from you.  If you want to talk more, please feel free to reopen this issue, create a new issue, or start a new discussion. 

And whenever you have time, let us know if you were able to get your [`contenteditable` example](https://github.com/grammarly/grammarly-for-developers/discussions/454) working too!

Thanks!

**Closed by AndrewDiMola** 2023-02-03 16:44 UTC
Labels: bug
