### ISSUE TITLE
[Bug]: Grammarly Button is spinning infinitely after initialization

### ISSUE THREAD

**Issue by virpo** [grammarly/grammarly-for-developers#24] opened 2022-03-09 16:08 UTC
### What package(s) are you seeing the problem in?

@grammarly/editor-sdk, @grammarly/editor-sdk-react

### SDK version

1.6.1

### Browser(s)

Chrome

### Operating system(s)

macOS

### Steps to reproduce

Minimal Repro: [CodeSandbox](https://codesandbox.io/s/grammarly-infinite-loading-eqmqtx?file=/src/Editors.js)

1. Open the link above
2. Click into the textarea
3. Type nothing
4. Observe Grammarly Button is spinning in the bottom right corner
5. The spinning only stops after typing something into the textarea

### What happened?

Grammarly Button is spinning

### What did you expect to happen?

No grammar check should be triggered without typing anything into the textarea

### Contact Details

peter@hraska.sk

**Comment by wachunga** [comment] 2022-03-09 17:25
Issue confirmed — thanks for reporting it. We're taking a look.

**Comment by wachunga** [comment] 2022-03-09 21:55
@virpo [1.6.2](https://developer.grammarly.com/docs/changelog/#_1-6-2-2022-03-09) has been released with the fix. I've verified in your codesandbox that it addresses the bug.

Thanks again for reporting it. It slipped through our tests because of a bug with our test editors initializing with " " instead of being empty. 🤦

**Closed by wachunga** 2022-03-09 21:55 UTC
Labels: bug

**Comment by virpo** [comment] 2022-03-09 23:49
Thanks!
I am glad I could've been of some help 🙂

**Comment by virpo** [comment] 2022-03-10 10:08
Just as a note, that might be useful for somebody
After upgrading to 1.6.2, Grammarly SDK didn't work locally for me until I've cleared my local storage
